import { query } from './db.js';

const setup = async () => {
  // tar bort och skapar nya tabeller om de redan finns. //!Endast för utveckling testning
  await query('DROP TABLE IF EXISTS books');
  await query('DROP TABLE IF EXISTS authors');

  // authors
  await query(`
    CREATE TABLE authors (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      first_name VARCHAR(20),
      last_name VARCHAR(20)
    )
  `);

  // books
  await query(`
    CREATE TABLE books (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      title VARCHAR(50),
      author_id INTEGER REFERENCES authors(id)
    )
  `);

  // Lägg in testdata
  await query(`
    INSERT INTO authors (first_name, last_name) VALUES
      ('Astrid', 'Lindgren'),
      ('J.K.', 'Rowling'),
      ('George', 'Orwell')
  `);

  await query(`
    INSERT INTO books (title, author_id) VALUES
      ('Pippi Långstrump', 1),
      ('Harry Potter and the Sorcerer''s Stone', 2),
      ('1984', 3),
      ('Animal Farm', 3)
  `);

  console.log('✅ authors och books skapade med testdata!');
};

setup();
